/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ============================================================
           Sitropix brand v1.0 (canonical) — point to CSS variables.
           ============================================================ */
        sx: {
          brand: {
            50: "var(--color-brand-50)",
            100: "var(--color-brand-100)",
            200: "var(--color-brand-200)",
            300: "var(--color-brand-300)",
            400: "var(--color-brand-400)",
            500: "var(--color-brand-500)",
            600: "var(--color-brand-600)",
            700: "var(--color-brand-700)",
            800: "var(--color-brand-800)",
            900: "var(--color-brand-900)",
            DEFAULT: "var(--color-brand-500)",
          },
          accent: {
            50: "var(--color-accent-50)",
            100: "var(--color-accent-100)",
            300: "var(--color-accent-300)",
            500: "var(--color-accent-500)",
            600: "var(--color-accent-600)",
            700: "var(--color-accent-700)",
            DEFAULT: "var(--color-accent-500)",
          },
          ink: {
            0: "var(--color-ink-0)",
            25: "var(--color-ink-25)",
            50: "var(--color-ink-50)",
            100: "var(--color-ink-100)",
            200: "var(--color-ink-200)",
            300: "var(--color-ink-300)",
            400: "var(--color-ink-400)",
            500: "var(--color-ink-500)",
            600: "var(--color-ink-600)",
            700: "var(--color-ink-700)",
            800: "var(--color-ink-800)",
            900: "var(--color-ink-900)",
          },
          success: {
            bg: "var(--color-success-bg)",
            fg: "var(--color-success-fg)",
            500: "var(--color-success-500)",
          },
          info: {
            bg: "var(--color-info-bg)",
            fg: "var(--color-info-fg)",
            500: "var(--color-info-500)",
          },
          warning: {
            bg: "var(--color-warning-bg)",
            fg: "var(--color-warning-fg)",
            500: "var(--color-warning-500)",
          },
          danger: {
            bg: "var(--color-danger-bg)",
            fg: "var(--color-danger-fg)",
            500: "var(--color-danger-500)",
          },
          closed: {
            bg: "var(--color-closed-bg)",
            fg: "var(--color-closed-fg)",
            500: "var(--color-closed-500)",
          },
        },
        /* ============================================================
           Legacy palette (kept while pages migrate). New code uses sx.*
           ============================================================ */
        "stone-1": "#F0EFEC",
        "stone-2": "#E8E7E3",
        "stone-3": "#C9C8C3",
        "stone-4": "#9B9A96",
        "stone-5": "#6B6A67",
        "stone-6": "#3D3C3A",
        "accent-gold": "#C4A35A",
        "gold-light": "#F5EDD8",
        "gold-dark": "#B39245",
        "off-white": "#F7F7F5",
        background: "#fdf8f7",
        "on-background": "#1c1b1b",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#494740",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#785d1b",
        "on-secondary-fixed": "#251a00",
        "on-secondary-fixed-variant": "#5b4300",
        "on-primary-fixed": "#1c1b19",
        "on-primary-fixed-variant": "#484644",
        "on-primary-container": "#868380",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#868384",
        "on-tertiary-fixed": "#1c1b1c",
        "on-tertiary-fixed-variant": "#484647",
        outline: "#7a776f",
        "outline-variant": "#cbc6bd",
        primary: "#000000",
        "primary-container": "#1c1b19",
        "primary-fixed": "#e6e2de",
        "primary-fixed-dim": "#cac6c2",
        secondary: "#755b18",
        "secondary-container": "#fdd88a",
        "secondary-fixed": "#ffdf9c",
        "secondary-fixed-dim": "#e5c276",
        tertiary: "#000000",
        "tertiary-container": "#1c1b1c",
        "tertiary-fixed": "#e6e1e2",
        "tertiary-fixed-dim": "#c9c5c6",
        "surface-bright": "#fdf8f7",
        "surface-dim": "#ddd9d8",
        "surface-variant": "#e6e2e1",
        "surface-container": "#f1edec",
        "surface-container-low": "#f7f3f2",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e6e2e1",
        "surface-tint": "#605e5b",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        "inverse-primary": "#cac6c2",
        success: "#2E6B4F",
        "success-bg": "#EAF3EE",
        warn: "#8A6200",
        "warn-bg": "#FBF4E2",
        info: "#2A5CA8",
        "info-bg": "#EAF0FA",
        error: "#A33030",
        "error-bg": "#FAE8E8",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        brand: {
          lime: "#080808",
          "lime-dim": "#353536",
          glow: "rgba(8, 8, 8, 0.2)",
        },
        admin: {
          lime: "#84CC16",
          "lime-dim": "#65a30d",
          glow: "rgba(132, 204, 22, 0.25)",
          canvas: "#0a0a0a",
          surface: "#15191C",
          "surface-alt": "#1C2126",
          border: "#24292E",
          "border-alt": "#2b3137",
        },
        zinc: {
          50: "#EBEDF1",
          100: "#EBEDF1",
          200: "#DDE0E6",
          300: "#D4D8DF",
          400: "#ACADB1",
          500: "#8E8F93",
          600: "#706F70",
          700: "#706F70",
          800: "#4A4A4D",
          900: "#353536",
          950: "#080808",
        },
        surface: {
          DEFAULT: "#fdf8f7",
          strong: "rgba(255, 255, 255, 0.9)",
          border: "rgba(112, 111, 112, 0.3)",
          glass: "rgba(255, 255, 255, 0.74)",
        },
        canvas: "#EBEDF1",
        ink: {
          muted: "#706F70",
          subtle: "#4A4A4D",
        },
      },
      fontFamily: {
        /* Brand v1.0 */
        display: ['"Bricolage Grotesque"', "ui-sans-serif", "system-ui", "sans-serif"],
        ui: ['"Inter Tight"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        /* Legacy aliases */
        sans: [
          '"Inter Tight"',
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        h1: ['"Bricolage Grotesque"', "Georgia", "serif"],
        h2: ['"Bricolage Grotesque"', "Georgia", "serif"],
        h3: ['"Inter Tight"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ['"Inter Tight"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ['"Inter Tight"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ['"Inter Tight"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        caption: ['"Inter Tight"', "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ['"JetBrains Mono"', '"IBM Plex Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        /* Brand v1.0 type scale */
        "sx-2xs": ["0.6875rem", { lineHeight: "1.4", letterSpacing: "0.12em", fontWeight: "600" }],
        "sx-xs": ["0.75rem", { lineHeight: "1.45", fontWeight: "400" }],
        "sx-sm": ["0.8125rem", { lineHeight: "1.5", fontWeight: "400" }],
        "sx-base": ["0.9375rem", { lineHeight: "1.5", fontWeight: "400" }],
        "sx-md": ["1rem", { lineHeight: "1.5", fontWeight: "400" }],
        "sx-lg": ["1.125rem", { lineHeight: "1.4", fontWeight: "500" }],
        "sx-xl": ["1.375rem", { lineHeight: "1.25", fontWeight: "600" }],
        "sx-2xl": ["1.75rem", { lineHeight: "1.15", fontWeight: "600" }],
        "sx-3xl": ["2.5rem", { lineHeight: "1.1", fontWeight: "500", letterSpacing: "-0.02em" }],
        "sx-4xl": ["4rem", { lineHeight: "1.1", fontWeight: "500", letterSpacing: "-0.02em" }],
        /* Legacy */
        h1: ["40px", { lineHeight: "1.1", fontWeight: "400" }],
        h2: ["28px", { lineHeight: "1.2", fontWeight: "400" }],
        h3: ["18px", { lineHeight: "1.35", fontWeight: "500" }],
        body: ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.65", fontWeight: "400" }],
        caption: ["11px", { lineHeight: "1.4", letterSpacing: "0.08em", fontWeight: "500" }],
        mono: ["13px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      borderRadius: {
        "sx-xs": "2px",
        "sx-sm": "4px",
        "sx-md": "6px",
        "sx-lg": "10px",
        "sx-xl": "16px",
        "sx-2xl": "24px",
      },
      boxShadow: {
        glass: "0 10px 26px rgba(53, 53, 54, 0.12)",
        lift: "0 18px 40px rgba(53, 53, 54, 0.18)",
        glow: "0 0 0 1px rgba(8, 8, 8, 0.2), 0 0 24px rgba(53, 53, 54, 0.12)",
        "sx-sm": "0 1px 2px rgba(17, 17, 16, 0.04), 0 1px 1px rgba(17, 17, 16, 0.03)",
        "sx-md": "0 4px 8px -2px rgba(17, 17, 16, 0.06), 0 2px 4px -2px rgba(17, 17, 16, 0.04)",
        "sx-lg": "0 12px 24px -6px rgba(17, 17, 16, 0.08), 0 4px 8px -4px rgba(17, 17, 16, 0.04)",
        "sx-xl": "0 24px 48px -12px rgba(17, 17, 16, 0.12)",
        "sx-focus": "0 0 0 3px rgba(21, 114, 140, 0.25)",
      },
      spacing: {
        gutter: "24px",
      },
      backgroundImage: {
        "hero-mesh":
          "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(172, 173, 177, 0.18), transparent), radial-gradient(ellipse 60% 40% at 100% 0%, rgba(212, 216, 223, 0.2), transparent), radial-gradient(ellipse 50% 30% at 0% 20%, rgba(112, 111, 112, 0.12), transparent)",
        "card-shine": "linear-gradient(135deg, rgba(255,255,255,0.08) 0%, transparent 50%)",
        "sx-hero": "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(21,114,140,0.10), transparent), radial-gradient(ellipse 60% 40% at 100% 0%, rgba(242,106,71,0.08), transparent)",
      },
      transitionTimingFunction: {
        "sx-standard": "cubic-bezier(0.2, 0, 0, 1)",
        "sx-emphasis": "cubic-bezier(0.3, 0, 0, 1)",
        "sx-exit": "cubic-bezier(0.4, 0, 1, 1)",
      },
      transitionDuration: {
        "sx-instant": "80ms",
        "sx-fast": "150ms",
        "sx-base": "220ms",
        "sx-slow": "360ms",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.6s ease-out forwards",
        "fade-up-delay": "fade-up 0.6s ease-out 0.1s forwards",
        "fade-up-delay-2": "fade-up 0.6s ease-out 0.2s forwards",
      },
    },
  },
  plugins: [],
};
